version: '3.8'

services:
  web:
    build: ./flask/services/web
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./flask/services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.dev
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web